In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent

print(PROJECT_ROOT)

c:\Users\ACER\OneDrive\Desktop\wind-aware-air-quality-forecasting

In [2]:
weather = pd.read_csv(
    PROJECT_ROOT /
    "data/raw/weather/Bagdol/Bagdol_2021.csv"
)

weather.head()

,timestamp,temperature,humidity,dew_point,pressure,wind_speed,wind_direction,precipitation,station,latitude,longitude
0,2021-01-01T00:00,7.5,60,0.3,871.0,4.4,171,0.0,Bagdol,27.671706,85.301619
1,2021-01-01T01:00,6.7,58,-0.9,870.1,3.7,169,0.0,Bagdol,27.671706,85.301619
2,2021-01-01T02:00,5.9,55,-2.4,869.5,3.3,167,0.0,Bagdol,27.671706,85.301619
3,2021-01-01T03:00,5.5,49,-4.3,869.4,2.6,164,0.0,Bagdol,27.671706,85.301619
4,2021-01-01T04:00,5.5,43,-6.0,869.3,3.3,167,0.0,Bagdol,27.671706,85.301619

In [3]:
air = pd.read_csv(
    PROJECT_ROOT /
    "data/raw/air_quality/Bagdol/Bagdol_2026.csv"
)

air.head()

                   timestamp      pm2_5
0  2026-02-06T13:45:00+05:45  52.603111
1  2026-02-06T14:45:00+05:45  65.027667
2  2026-02-06T15:45:00+05:45  52.348805
3  2026-02-06T16:45:00+05:45  57.167818
4  2026-02-06T17:45:00+05:45  70.019000

In [9]:
merged = pd.read_csv("../data/processed/merged/Embassy Kathmandu.csv")

merged[merged["pm2_5"].notna()].head(5)

,timestamp,temperature,humidity,dew_point,pressure,wind_speed,wind_direction,precipitation,station,latitude,longitude,pm2_5
5,2021-01-01 05:00:00,2.6,84,0.1,863.2,5.4,132,0.0,Embassy Kathmandu,27.738703,85.336206,96.0
6,2021-01-01 06:00:00,2.8,81,-0.1,863.7,6.4,133,0.0,Embassy Kathmandu,27.738703,85.336206,91.0
7,2021-01-01 07:00:00,4.0,76,0.1,864.9,7.4,129,0.0,Embassy Kathmandu,27.738703,85.336206,114.0
8,2021-01-01 08:00:00,10.0,55,1.4,868.8,6.9,129,0.0,Embassy Kathmandu,27.738703,85.336206,141.0
9,2021-01-01 09:00:00,14.6,27,-4.3,871.4,1.6,153,0.0,Embassy Kathmandu,27.738703,85.336206,167.0

In [10]:
trimmed = pd.read_csv("../data/processed/trimmed/Embassy Kathmandu.csv")
trimmed.head(10)

,timestamp,temperature,humidity,dew_point,pressure,wind_speed,wind_direction,precipitation,station,latitude,longitude,pm2_5
0,2021-01-01 05:00:00,2.6,84,0.1,863.2,5.4,132,0.0,Embassy Kathmandu,27.738703,85.336206,96.0
1,2021-01-01 06:00:00,2.8,81,-0.1,863.7,6.4,133,0.0,Embassy Kathmandu,27.738703,85.336206,91.0
2,2021-01-01 07:00:00,4.0,76,0.1,864.9,7.4,129,0.0,Embassy Kathmandu,27.738703,85.336206,114.0
3,2021-01-01 08:00:00,10.0,55,1.4,868.8,6.9,129,0.0,Embassy Kathmandu,27.738703,85.336206,141.0
4,2021-01-01 09:00:00,14.6,27,-4.3,871.4,1.6,153,0.0,Embassy Kathmandu,27.738703,85.336206,167.0
5,2021-01-01 10:00:00,16.2,23,-4.8,871.6,3.1,306,0.0,Embassy Kathmandu,27.738703,85.336206,109.0
6,2021-01-01 11:00:00,17.3,23,-3.8,871.4,5.4,312,0.0,Embassy Kathmandu,27.738703,85.336206,71.0
7,2021-01-01 12:00:00,18.2,23,-3.3,870.7,7.9,309,0.0,Embassy Kathmandu,27.738703,85.336206,54.0
8,2021-01-01 13:00:00,18.1,25,-2.5,869.8,9.5,307,0.0,Embassy Kathmandu,27.738703,85.336206,63.0
9,2021-01-01 14:00:00,17.3,28,-1.2,869.0,9.3,306,0.0,Embassy Kathmandu,27.738703,85.336206,40.0

In [11]:
trimmed = pd.read_csv(
    PROJECT_ROOT /
    "data/processed/trimmed/Bagdol.csv"
)

trimmed.head()

,timestamp,temperature,humidity,dew_point,pressure,wind_speed,wind_direction,precipitation,station,latitude,longitude,pm2_5
0,2026-02-06 13:00:00,18.8,46,7.0,875.3,8.3,326,0.0,Bagdol,27.671706,85.301619,52.603111
1,2026-02-06 14:00:00,18.2,50,7.7,874.6,8.6,327,0.0,Bagdol,27.671706,85.301619,65.027667
2,2026-02-06 15:00:00,17.3,54,7.9,873.7,9.1,335,0.0,Bagdol,27.671706,85.301619,52.348805
3,2026-02-06 16:00:00,16.0,59,8.1,873.1,7.1,350,0.0,Bagdol,27.671706,85.301619,57.167818
4,2026-02-06 17:00:00,13.3,72,8.4,872.2,3.0,17,0.0,Bagdol,27.671706,85.301619,70.019000

In [17]:
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

featured = pd.read_csv(
    PROJECT_ROOT / "data/processed/featured/Embassy Kathmandu.csv"
)

# Show first rows where all engineered features are available
featured.dropna().head()

,timestamp,temperature,humidity,dew_point,pressure,wind_speed,wind_direction,precipitation,station,latitude,longitude,pm2_5,hour,day,month,weekday,lag_1,lag_3,lag_6,lag_12,lag_24,rolling_mean_3,rolling_mean_6,rolling_mean_24,rolling_std_3,rolling_std_6,rolling_std_24,wind_u,wind_v,hour_sin,hour_cos,month_sin,month_cos
72,2021-01-04 05:00:00,13.8,49,3.4,869.0,3.0,76,0.0,Embassy Kathmandu,27.738703,85.336206,107.0,5,4,1,0,102.0,127.0,190.0,64.0,90.0,116.666667,125.833333,114.708333,21.221059,17.336859,45.340719,0.725766,2.910887,0.965926,2.588190e-01,0.5,0.866025
73,2021-01-04 06:00:00,11.3,65,4.8,868.0,3.7,151,0.0,Embassy Kathmandu,27.738703,85.336206,119.0,6,4,1,0,107.0,141.0,138.0,123.0,85.0,109.333333,122.666667,116.125000,8.736895,16.378848,44.901160,-3.236093,1.793796,1.000000,6.123234e-17,0.5,0.866025
74,2021-01-04 07:00:00,11.9,61,4.6,868.9,4.8,138,0.1,Embassy Kathmandu,27.738703,85.336206,70.0,7,4,1,0,119.0,102.0,140.0,119.0,111.0,98.666667,111.000000,114.416667,25.540817,24.486731,45.874040,-3.567095,3.211827,0.965926,-2.588190e-01,0.5,0.866025
75,2021-01-04 08:00:00,13.2,61,5.8,869.8,6.9,141,0.0,Embassy Kathmandu,27.738703,85.336206,164.0,8,4,1,0,70.0,107.0,127.0,99.0,149.0,117.666667,117.166667,115.041667,47.014182,32.627698,46.464085,-5.362307,4.342311,0.866025,-5.000000e-01,0.5,0.866025
76,2021-01-04 09:00:00,15.7,55,6.8,871.2,6.4,133,0.0,Embassy Kathmandu,27.738703,85.336206,149.0,9,4,1,0,164.0,119.0,141.0,114.0,153.0,127.666667,118.500000,114.875000,50.500825,33.933759,46.328987,-4.364790,4.680664,0.707107,-7.071068e-01,0.5,0.866025

In [14]:
train = pd.read_csv(
    PROJECT_ROOT /
    "data/processed/split/train/Bagdol.csv"
)

train.head()

,timestamp,temperature,humidity,dew_point,pressure,wind_speed,wind_direction,precipitation,station,latitude,...,rolling_std_3,rolling_std_6,rolling_std_24,wind_u,wind_v,hour_sin,hour_cos,month_sin,month_cos,target_pm2_5
0,2026-02-06 13:00:00,18.8,46,7.0,875.3,8.3,326,0.0,Bagdol,27.671706,...,NaN,NaN,NaN,6.881012,-4.641301,-0.258819,-0.965926,0.866025,0.5,65.027667
1,2026-02-06 14:00:00,18.2,50,7.7,874.6,8.6,327,0.0,Bagdol,27.671706,...,NaN,NaN,NaN,7.212567,-4.683896,-0.500000,-0.866025,0.866025,0.5,52.348805
2,2026-02-06 15:00:00,17.3,54,7.9,873.7,9.1,335,0.0,Bagdol,27.671706,...,7.247848,NaN,NaN,8.247401,-3.845826,-0.707107,-0.707107,0.866025,0.5,57.167818
3,2026-02-06 16:00:00,16.0,59,8.1,873.1,7.1,350,0.0,Bagdol,27.671706,...,6.399917,NaN,NaN,6.992135,-1.232902,-0.866025,-0.500000,0.866025,0.5,70.019000
4,2026-02-06 17:00:00,13.3,72,8.4,872.2,3.0,17,0.0,Bagdol,27.671706,...,9.134290,NaN,NaN,2.868914,0.877115,-0.965926,-0.258819,0.866025,0.5,87.388667

In [15]:
validation = pd.read_csv(
    PROJECT_ROOT /
    "data/processed/split/validation/Bagdol.csv"
)

validation.head()

,timestamp,temperature,humidity,dew_point,pressure,wind_speed,wind_direction,precipitation,station,latitude,...,rolling_std_3,rolling_std_6,rolling_std_24,wind_u,wind_v,hour_sin,hour_cos,month_sin,month_cos,target_pm2_5
0,2026-04-25 15:00:00,23.2,61,15.3,873.0,3.1,306,0.0,Bagdol,27.671706,...,5.251984,3.941446,25.947033,1.822134,-2.507953,-0.707107,-7.071068e-01,0.866025,-0.5,60.4
1,2026-04-25 16:00:00,23.2,62,15.4,872.8,3.9,13,0.0,Bagdol,27.671706,...,3.572581,5.155967,24.820150,3.800043,0.877309,-0.866025,-5.000000e-01,0.866025,-0.5,71.2
2,2026-04-25 17:00:00,18.9,84,16.1,872.4,7.0,44,0.0,Bagdol,27.671706,...,6.609085,8.563975,23.774493,5.035379,4.862609,-0.965926,-2.588190e-01,0.866025,-0.5,72.2
3,2026-04-25 18:00:00,18.2,94,17.2,872.3,5.4,143,1.5,Bagdol,27.671706,...,6.543190,9.355212,21.872496,-4.312632,3.249801,-1.000000,-1.836970e-16,0.866025,-0.5,53.6
4,2026-04-25 19:00:00,17.8,97,17.3,871.8,6.7,156,1.1,Bagdol,27.671706,...,10.461995,8.222510,18.452917,-6.120755,2.725136,-0.965926,2.588190e-01,0.866025,-0.5,51.0